### ISSUE TITLE
Models missing

### ISSUE THREAD

**Issue by Gitsmackt** [zpetty33/GMStranded#3]
Hey, I'm receiving these errors when I load up my server, causing me not to be able to actually use the ore nodes

Model missing: models/ore_nodes/stone_node/stone_node.mdl
Model missing: models/ore_nodes/coal_node/coal_node.mdl
Model missing: models/ore_nodes/iron_node/iron_node.mdl
Model missing: models/ore_nodes/gold_node/gold_node.mdl
Model missing: models/ore_nodes/naq_node/naq_node.mdl
Model missing: models/ore_nodes/trin_node/trin_node.mdl
Model missing: models/ore_nodes/mith_node/mith_node.mdl
Model missing: models/props_foliage/tree_pine04.mdl
Model missing: models/props_foliage/tree_palm_dust01.mdl
Model missing: models/ore_nodes/stone_node/stone_node.mdl
Model missing: models/ore_nodes/trin_node/trin_node.mdl

Do you have the models?

**Comment by zpetty33** [comment]
These are in the content packs on the workshop. Make sure your server is subscribed to these as well as your clients who are joining your server. The server needs to have it otherwise they won't function properly.
