### ISSUE TITLE
How to spawn in trees and rocks, antlion burrows, etc?

### ISSUE THREAD

**Issue by grimsikk** [zpetty33/GMStranded#4]
This was a basic feature in original stranded, but original stranded is broken and saves don't work.

I switched to this so that I could set up a map and then be able to save the props and progress on building and stuff.

**Comment by zpetty33** [comment]
Hi,

There is no easy way to do this, unfortunately. I always did it manually.

First, turn on edit mode... again no easy way to do this.. run the following in your server's console

lua_run SGS.inedit = true

What you will need to do then is spawn the trees and rocks manually using some form of Entity spawn command. ULX has one.

Entities are:

		gms_tree
		gms_tree2
		gms_tree3
		gms_tree4
		gms_tree5
		gms_tree6
		gms_tree7
		gms_ironnode
		gms_stonenode
		gms_coalnode
		gms_silvernode
		gms_naquadahnode
		gms_triniumnode
		gms_goldnode
		gms_mithrilnode
		gms_platinumnode
		npc_vortigaunt
		npc_breen
		npc_kleiner
		gms_antlionspawner

Once you have spawned in what you want where you want them, you will need to run the command to save the entities. The command is as follows:

lua_run SGS_BuildEntityList()


Then turn off Edit mod.

lua_run SGS.inedit = false

and then restart your server and it should load.


Sorry this is so difficult, but again.. it was never intended to be released so I never make it "user friendly" because it always worked for me. :)

Good luck!

**Comment by grimsikk** [comment]
Oh wow this is a huge help, I use ulx for my cyberpunk server so that works out. 

Will the build entity list command save props and plants that are placed by players as well?

Either way thank you for the quick reply and list of commands.

**Comment by zpetty33** [comment]
No, it only saves entities that I listed in the first response. You should set up trees and stuff with no other players on, and on a clean server.

If you want to save what player's a placing, you need to use the command sgs_saveall

This will save a file of all props that will reload when the server restarts.

Unfortunately, plants/pets/and chairs are not saved. Everything else is.. including resource boxes and the resources inside of caches.

**Comment by zpetty33** [comment]
The server also auto saves player's stuff every so often. This acts as a server crash protection script in case the server crashes, people won't lose all of their stuff. If you want to restart the server and remove everything, you have to go into garrysmod\data\sgstranded\crashrecovery and remove the file from there while your server is offline and then start the server and it'll load with no player props.

**Comment by grimsikk** [comment]
Awesome I'll have to try that, but first...for some reason its saying in console that I don't have a bunch of the sgs commands:

Loaded character successfully.
Last visited on Tuesday 10/02/18. Welcome Back!
Character Saved!
souma has joined the server.
Unknown command: sgs_refreshspells
Unknown command: sgs_refreshspells
Unknown command: sgs_refreshoptions
Unknown command: sgs_refreshresources
Unknown command: sgs_refreshresources
Unknown command: sgs_refreshmodelpanel
Unknown command: sgs_refreshresources
Unknown command: sgs_refreshpmodels
Unknown command: sgs_refreshfarming
Unknown command: sgs_refreshvc
Unknown command: sgs_refreshfarming
Unknown command: sgs_refreshfarming
Unknown command: sgs_refreshtools


it's also repeatedly spamming this in console:

[ERROR] gamemodes/gmstranded/gamemode/modules/server/sv_bossai.lua:332: bad argument #1 to 'find' (string expected, got nil)
  1. find - [C]:-1
   2. v - gamemodes/gmstranded/gamemode/modules/server/sv_bossai.lua:332
    3. unknown - lua/includes/modules/hook.lua:84

**Comment by grimsikk** [comment]
I'd like to add that everything else seems to be working so far despite these 2 random issues.

**Comment by zpetty33** [comment]
The first is an old bug that is related to the Q menu. Safe to ignore.

The second is interesting as it shouldn't error like that. You can remove the hook from line 327 to line 334 entirely and it will go away, it just won't clean up the manhack gibs.

**Comment by grimsikk** [comment]
ah ok. thank you very much for all the help, it really means a lot! I'll be sure to let you know if I need anything else. :) Great game-mode, I'm loving it so far.
