### ISSUE TITLE
last_world_change error appears every time someone jumps

### ISSUE THREAD

**Issue by grimsikk** [zpetty33/GMStranded#5]
I'm trying to use a non-stranded map so I understand if this is a result of that. I appreciate the help though.
Every time I jump this appears:

[ERROR] gamemodes/gmstranded/gamemode/init.lua:5170: attempt to perform arithmetic on field 'last_world_change' (a nil value)
  1. unknown - gamemodes/gmstranded/gamemode/init.lua:5170

Side note: 
This error appears randomly and when I load in:

[ERROR] gamemodes/gmstranded/gamemode/modules/client/skybox/cl_worldskies.lua:44: attempt to index local 'tblNewWorld' (a nil value)
  1. WorldChanged - gamemodes/gmstranded/gamemode/modules/client/skybox/cl_worldskies.lua:44
   2. OnBloodMoonStop - gamemodes/gmstranded/gamemode/modules/client/skybox/cl_worldskies.lua:59
    3. v - gamemodes/gmstranded/gamemode/modules/client/skybox/cl_worldskies.lua:21
     4. Call - lua/includes/modules/hook.lua:84
      5. func - gamemodes/gmstranded/gamemode/modules/sh_worlds.lua:116
       6. unknown - lua/includes/extensions/net.lua:32

**Comment by grimsikk** [comment]
also, side note:
This keeps appearing whenever I try to make a Workbench:

[ERROR] gamemodes/gmstranded/gamemode/modules/server/sv_processes.lua:3113: attempt to index a nil value
  1. SGS_BuildStructure_Start - gamemodes/gmstranded/gamemode/modules/server/sv_processes.lua:3113
   2. unknown - gamemodes/gmstranded/gamemode/init.lua:874
    3. unknown - lua/includes/modules/concommand.lua:54

**Comment by zpetty33** [comment]
Looks like you're using a map other than the one provided. That's fine but you have to set up the world file. Take a look in the gamemode file under modules and there is a worlds folder. See if you can figure out how to make a new one for your map.
